apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fabiossena/terraform-aws-eks-apps
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook