
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dvn-
nameSuffix: -prod

resources:
- deployment.yml
- service.yml

images:
- name: 801528680042.dkr.ecr.us-east-1.amazonaws.com/production/fss-site-v2
  newName: 801528680042.dkr.ecr.us-east-1.amazonaws.com/production/fss-site-v2
  newTag: a83a54ade2aa86f3424ccf2b7e6cea6c684b7c69
