resources:
  - nodeclass.yaml
  - nodepool.yaml

configMapGenerator:
  - name: cluster-config
    literals:
      - CLUSTER_NAME=fss-march-eks-cluster
      - CLUSTER_ROLE=fss-march-eks-cluster-role

replacements:
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          kind: EC2NodeClass
          name: default
        fieldPaths:
          - spec.subnetSelectorTerms.0.tags.karpenter\.sh/discovery
          - spec.securityGroupSelectorTerms.0.tags.karpenter\.sh/discovery
          - spec.tags.karpenter\.sh/discovery

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.CLUSTER_ROLE
    targets:
      - select:
          kind: EC2NodeClass
          name: default
        fieldPaths:
          - spec.role