apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  limits:
    cpu: "200"

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s

  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      expireAfter: 24h

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t2", "t3"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["micro", "small"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]

        # - key: kubernetes.io/arch
        #   operator: In
        #   values: ["amd64", "arm64"]
        # - key: karpenter.sh/capacity-type
        #   operator: In
        #   values: ["on-demand"] # "spot", 
        # # - key: karpenter.k8s.aws/instance-category
        # #   operator: In
        # #   values: ["c", "m"]
        # # ABAIXO NOVO
        # - key: karpenter.k8s.aws/instance-family
        #   operator: In
        #   values: ["t2", "t3", "t4g"]  # Famílias Free Tier
        # - key: karpenter.k8s.aws/instance-size
        #   operator: In
        #   values: ["micro", "small"]  # Tamanhos Free Tier
        # - key: karpenter.k8s.aws/instance-generation
        #   operator: Gt
        #   values: ["2"]  # Gerações mais recentes